/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import java.time.LocalDateTime;

import ENTITY.ChiTietVe;
import ENTITY.VeMayBay;

/**
 *
 * @author ADMIN
 */
public class Form_Ve extends javax.swing.JPanel {
	private VeMayBay veMayBay; 
	private ChiTietVe chiTietVe; 
	
	/**
	 * Creates new form Form_Ve
	 */
	public Form_Ve(VeMayBay vmb, ChiTietVe ctv) {
		this.veMayBay = vmb; 
		this.chiTietVe = ctv; 
		
		
		initComponents();
		duaDuLieu();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        textTenHangBay = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textTenKhachHang = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textNoiDi = new javax.swing.JLabel();
        textNoiDen = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textSoGhe = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textNgayDi = new javax.swing.JLabel();
        textGioDi = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        textTenKhachHang2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        textNoiDi2 = new javax.swing.JLabel();
        textNoiDen2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        textSoGhe2 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setPreferredSize(new java.awt.Dimension(500, 250));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 250));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(21, 115, 135));
        jPanel2.setPreferredSize(new java.awt.Dimension(865, 40));

        textTenHangBay.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        textTenHangBay.setForeground(new java.awt.Color(255, 255, 255));
        textTenHangBay.setText("TenHangBay");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(textTenHangBay, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(565, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textTenHangBay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(21, 115, 135));
        jLabel1.setText("Tên Khách Hàng");

        textTenKhachHang.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        textTenKhachHang.setForeground(new java.awt.Color(21, 115, 135));
        textTenKhachHang.setText("jLabel2");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(21, 115, 135));
        jLabel2.setText("Từ:");

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(21, 115, 135));
        jLabel3.setText("Đến:");

        textNoiDi.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        textNoiDi.setForeground(new java.awt.Color(21, 115, 135));
        textNoiDi.setText("jLabel4");

        textNoiDen.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        textNoiDen.setForeground(new java.awt.Color(21, 115, 135));
        textNoiDen.setText("jLabel5");

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(21, 115, 135));
        jLabel4.setText("Ghế");

        textSoGhe.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        textSoGhe.setForeground(new java.awt.Color(21, 115, 135));
        textSoGhe.setText("jLabel5");

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(21, 115, 135));
        jLabel5.setText("Ngày Đi:");

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(21, 115, 135));
        jLabel6.setText("Giờ Đi:");

        textNgayDi.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        textNgayDi.setForeground(new java.awt.Color(21, 115, 135));
        textNgayDi.setText("jLabel7");

        textGioDi.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        textGioDi.setForeground(new java.awt.Color(21, 115, 135));
        textGioDi.setText("jLabel8");

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(21, 115, 135));
        jLabel7.setText("Tên Khách Hàng");

        textTenKhachHang2.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        textTenKhachHang2.setForeground(new java.awt.Color(21, 115, 135));
        textTenKhachHang2.setText("jLabel8");

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(21, 115, 135));
        jLabel8.setText("Từ:");

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(21, 115, 135));
        jLabel9.setText("Đến:");

        textNoiDi2.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        textNoiDi2.setForeground(new java.awt.Color(21, 115, 135));
        textNoiDi2.setText("jLabel10");

        textNoiDen2.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        textNoiDen2.setForeground(new java.awt.Color(21, 115, 135));
        textNoiDen2.setText("jLabel11");

        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(21, 115, 135));
        jLabel12.setText("Số hiện máy bay: ");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(21, 115, 135));
        jLabel13.setText("AA 1387");

        jLabel14.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(21, 115, 135));
        jLabel14.setText("Ghế:");

        textSoGhe2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textSoGhe2.setForeground(new java.awt.Color(21, 115, 135));
        textSoGhe2.setText("jLabel15");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textNoiDen))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textNoiDi))
                        .addComponent(jLabel1))
                    .addComponent(textTenKhachHang))
                .addGap(133, 133, 133)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(textSoGhe)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textGioDi)
                            .addComponent(textNgayDi))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(textNoiDi2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textNoiDen2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(77, 77, 77)
                        .addComponent(jLabel14))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(textTenKhachHang2)
                        .addGap(153, 153, 153)
                        .addComponent(textSoGhe2)))
                .addGap(121, 121, 121))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textTenKhachHang)
                            .addComponent(textSoGhe))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(textNoiDi)
                            .addComponent(jLabel5)
                            .addComponent(textNgayDi))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(textNoiDen)
                            .addComponent(jLabel6)
                            .addComponent(textGioDi)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textTenKhachHang2)
                            .addComponent(textSoGhe2))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(textNoiDi2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(textNoiDen2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

	private void duaDuLieu() {
		// Lấy giá trị LocalDateTime từ chiTietVe
	    LocalDateTime thoiGianDi = chiTietVe.getMaTrangThaiGhe().getMaLichBay().getThoiGianDi();

	    // Hiển thị ngày tháng năm cho textNgayDi
	    textNgayDi.setText(thoiGianDi.getDayOfMonth() + "/" + thoiGianDi.getMonthValue() + "/" + thoiGianDi.getYear());

	    // Hiển thị giờ phút giây cho textGioDi
	    textGioDi.setText(thoiGianDi.getHour() + ":" + thoiGianDi.getMinute() + ":" + thoiGianDi.getSecond());

	    // Các thông tin khác giữ nguyên
	    textNoiDen.setText(chiTietVe.getMaTrangThaiGhe().getMaLichBay().getNoiDen());
	    textNoiDen2.setText(chiTietVe.getMaTrangThaiGhe().getMaLichBay().getNoiDen());
	    textNoiDi.setText(chiTietVe.getMaTrangThaiGhe().getMaLichBay().getNoiDi());
	    textNoiDi2.setText(chiTietVe.getMaTrangThaiGhe().getMaLichBay().getNoiDi());
	    textSoGhe.setText(chiTietVe.getMaTrangThaiGhe().getMaGhe().getMaGhe());
	    textSoGhe2.setText(chiTietVe.getMaTrangThaiGhe().getMaGhe().getMaGhe());
	    textTenHangBay.setText(veMayBay.getMaHangBay().getTenHangBay());
	    textTenKhachHang.setText(chiTietVe.getMaKhachHang().getTenKhachHang());
	    textTenKhachHang2.setText(chiTietVe.getMaKhachHang().getTenKhachHang());
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel textGioDi;
    private javax.swing.JLabel textNgayDi;
    private javax.swing.JLabel textNoiDen;
    private javax.swing.JLabel textNoiDen2;
    private javax.swing.JLabel textNoiDi;
    private javax.swing.JLabel textNoiDi2;
    private javax.swing.JLabel textSoGhe;
    private javax.swing.JLabel textSoGhe2;
    private javax.swing.JLabel textTenHangBay;
    private javax.swing.JLabel textTenKhachHang;
    private javax.swing.JLabel textTenKhachHang2;
    // End of variables declaration//GEN-END:variables
}
