/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import java.util.ArrayList;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ENTITY.KhachHang;
import DAO.DAO_KhachHang;

/**
 *
 * @author ADMIN
 */
public class GUI_KhachHang extends javax.swing.JPanel {
	// Bien table
	private String tieude[] = { "Mã Khách Hàng", "Tên Khách Hàng", "Số Điện Thoại", "Email", "Giới Tính",
			"Số Căn Cước" };
	private DefaultTableModel model = new DefaultTableModel(tieude, 0);

	// Dao
	private DAO_KhachHang dao_KhachHang = new DAO_KhachHang();

	// list
	private ArrayList<KhachHang> listKhachHang;
	//

	/**
	 * Creates new form GUI_KhachHang
	 */
	public GUI_KhachHang() {
		listKhachHang = dao_KhachHang.getallTBKhachHang();

		initComponents();

		duaDuLieuVaoModule();

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gender = new javax.swing.ButtonGroup();
        header = new javax.swing.JPanel();
        content = new javax.swing.JPanel();
        ThongtinKH = new javax.swing.JPanel();
        maKH = new javax.swing.JLabel();
        maKHtxt = new javax.swing.JTextField();
        email = new javax.swing.JLabel();
        emailtxt = new javax.swing.JTextField();
        CCCD = new javax.swing.JLabel();
        cccdtxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        sodienthoai = new javax.swing.JLabel();
        gioitinh = new javax.swing.JLabel();
        gtnam = new javax.swing.JRadioButton();
        gtnu = new javax.swing.JRadioButton();
        hovatentxt = new javax.swing.JTextField();
        sodienthoaitxt = new javax.swing.JTextField();
        timkiem = new javax.swing.JLabel();
        timkiemtxt = new javax.swing.JTextField();
        nuttim = new javax.swing.JButton();
        nutDatLai = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        bangthongtin = new javax.swing.JTable();
        buttontxs = new javax.swing.JPanel();
        them = new javax.swing.JButton();
        capnhat = new javax.swing.JButton();
        xoa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        header.setLayout(new java.awt.BorderLayout());
        add(header, java.awt.BorderLayout.PAGE_START);

        ThongtinKH.setName(""); // NOI18N

        maKH.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        maKH.setText("Mã Khách Hàng");

        maKHtxt.setEditable(false);

        email.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        email.setText("Email");

        CCCD.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CCCD.setText("CCCD");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Họ và Tên");

        sodienthoai.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sodienthoai.setText("Số Điện Thoại");

        gioitinh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        gioitinh.setText("Giới Tính");

        gender.add(gtnam);
        gtnam.setText("Nam");

        gender.add(gtnu);
        gtnu.setText("Nữ");

        hovatentxt.setPreferredSize(new java.awt.Dimension(64, 30));

        timkiem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        timkiem.setText("Tìm Kiếm Khách Hàng Theo SDT");

        timkiemtxt.setPreferredSize(new java.awt.Dimension(64, 30));
        timkiemtxt.setRequestFocusEnabled(false);

        nuttim.setBackground(new java.awt.Color(25, 145, 166));
        nuttim.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nuttim.setForeground(new java.awt.Color(255, 255, 255));
        nuttim.setText("Tìm Kiếm");
        nuttim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuttimActionPerformed(evt);
            }
        });

        nutDatLai.setBackground(new java.awt.Color(25, 145, 166));
        nutDatLai.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nutDatLai.setForeground(new java.awt.Color(255, 255, 255));
        nutDatLai.setText("Đặt Lại");
        nutDatLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nutDatLaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ThongtinKHLayout = new javax.swing.GroupLayout(ThongtinKH);
        ThongtinKH.setLayout(ThongtinKHLayout);
        ThongtinKHLayout.setHorizontalGroup(
            ThongtinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThongtinKHLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(ThongtinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CCCD)
                    .addComponent(maKH)
                    .addComponent(maKHtxt)
                    .addComponent(email)
                    .addComponent(emailtxt)
                    .addComponent(cccdtxt, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE))
                .addGroup(ThongtinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ThongtinKHLayout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(gtnam)
                        .addGap(60, 60, 60)
                        .addComponent(gtnu)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ThongtinKHLayout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addGroup(ThongtinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hovatentxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sodienthoai)
                            .addComponent(gioitinh)
                            .addComponent(sodienthoaitxt, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(ThongtinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ThongtinKHLayout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addComponent(nutDatLai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ThongtinKHLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                                .addGroup(ThongtinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ThongtinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(timkiem)
                                        .addComponent(timkiemtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(nuttim, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(129, 129, 129))))
        );
        ThongtinKHLayout.setVerticalGroup(
            ThongtinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThongtinKHLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(ThongtinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maKH)
                    .addComponent(jLabel6)
                    .addComponent(timkiem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ThongtinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hovatentxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(timkiemtxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(maKHtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ThongtinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email)
                    .addComponent(sodienthoai)
                    .addComponent(nuttim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ThongtinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ThongtinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sodienthoaitxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nutDatLai)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ThongtinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gioitinh, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CCCD))
                .addGap(18, 18, 18)
                .addGroup(ThongtinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cccdtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gtnam)
                    .addComponent(gtnu))
                .addGap(19, 19, 19))
        );

        bangthongtin.setModel(model);
        bangthongtin.setRowHeight(30);
        bangthongtin.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                bangthongtinAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(bangthongtin);

        them.setBackground(new java.awt.Color(25, 145, 166));
        them.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        them.setForeground(new java.awt.Color(255, 255, 255));
        them.setText("Thêm");
        them.setPreferredSize(new java.awt.Dimension(150, 60));
        them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themActionPerformed(evt);
            }
        });

        capnhat.setBackground(new java.awt.Color(25, 145, 166));
        capnhat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        capnhat.setForeground(new java.awt.Color(255, 255, 255));
        capnhat.setText("Cập Nhật");
        capnhat.setPreferredSize(new java.awt.Dimension(150, 60));
        capnhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capnhatActionPerformed(evt);
            }
        });

        xoa.setBackground(new java.awt.Color(25, 145, 166));
        xoa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        xoa.setForeground(new java.awt.Color(255, 255, 255));
        xoa.setText("Xóa");
        xoa.setPreferredSize(new java.awt.Dimension(150, 60));
        xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttontxsLayout = new javax.swing.GroupLayout(buttontxs);
        buttontxs.setLayout(buttontxsLayout);
        buttontxsLayout.setHorizontalGroup(
            buttontxsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttontxsLayout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(them, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addComponent(capnhat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139)
                .addComponent(xoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        buttontxsLayout.setVerticalGroup(
            buttontxsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(buttontxsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(xoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(capnhat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(them, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(21, 115, 135));
        jLabel1.setText("QUẢN LÝ KHÁCH HÀNG");

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ThongtinKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1014, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(buttontxs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(ThongtinKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(buttontxs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(476, Short.MAX_VALUE))
        );

        add(content, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    private void capnhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capnhatActionPerformed
        // TODO add your handling code here:
    	 String maKH = maKHtxt.getText().trim();
    	    String hoTen = hovatentxt.getText().trim();
    	    String soDienThoai = sodienthoaitxt.getText().trim();
    	    String email = emailtxt.getText().trim();
    	    String cccd = cccdtxt.getText().trim();
    	    String gioiTinh = gtnam.isSelected() ? "Nam" : "Nữ";  // Lấy giá trị từ RadioButton

    	    // Kiểm tra xem các trường có rỗng không
    	    if (maKH.isEmpty() || hoTen.isEmpty() || soDienThoai.isEmpty() || email.isEmpty() || cccd.isEmpty()) {
    	        JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin khách hàng!", "Lỗi", JOptionPane.ERROR_MESSAGE);
    	        return;
    	    }

    	    // Tạo đối tượng KhachHang từ các giá trị lấy được từ JTextField
    	    KhachHang kh = new KhachHang(maKH, hoTen, soDienThoai, email, gioiTinh, cccd);

    	    // Gọi phương thức cập nhật từ lớp DAO_KhachHang
    	    DAO_KhachHang dao = new DAO_KhachHang();
    	    boolean isUpdated = dao.updateCustomer(kh);
    	    
    	    // Thông báo cho người dùng về kết quả cập nhật
    	    if (isUpdated) {
    	    	model.setRowCount(0);
				listKhachHang = dao_KhachHang.getallTBKhachHang();
				duaDuLieuVaoModule();
				
    	        JOptionPane.showMessageDialog(this, "Cập nhật thông tin khách hàng thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
    	    } else {
    	        JOptionPane.showMessageDialog(this, "Lỗi khi cập nhật thông tin khách hàng!", "Lỗi", JOptionPane.ERROR_MESSAGE);
    	    }
    }//GEN-LAST:event_capnhatActionPerformed

    private void nutDatLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nutDatLaiActionPerformed
        // TODO add your handling code here:
    	maKHtxt.setText(null);
    	hovatentxt.setText(null);
    	emailtxt.setText(null);
    	sodienthoaitxt.setText(null);
    	cccdtxt.setText(null);
    	timkiemtxt.setText(null);
    	gender.clearSelection();
    }//GEN-LAST:event_nutDatLaiActionPerformed

    private void bangthongtinAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_bangthongtinAncestorAdded
        // TODO add your handling code here:
    	 bangthongtin.getSelectionModel().addListSelectionListener(e -> {
 	        // Kiểm tra xem có dòng nào được chọn không
 	        int selectedRow = bangthongtin.getSelectedRow();
 	        if (selectedRow != -1) {
 	            // Lấy dữ liệu từ dòng được chọn
 	            String maKH = bangthongtin.getValueAt(selectedRow, 0).toString();
 	            String hoTen = bangthongtin.getValueAt(selectedRow, 1).toString();
 	            String soDienThoai = bangthongtin.getValueAt(selectedRow, 2).toString();
 	            String email = bangthongtin.getValueAt(selectedRow, 3).toString();
 	            String gioiTinh = bangthongtin.getValueAt(selectedRow, 4).toString();
 	            String cccd = bangthongtin.getValueAt(selectedRow, 5).toString();

 	            // Gán dữ liệu vào các JTextField
 	            maKHtxt.setText(maKH);
 	            hovatentxt.setText(hoTen);
 	            sodienthoaitxt.setText(soDienThoai);
 	            emailtxt.setText(email);
 	            cccdtxt.setText(cccd);

 	            // Gán giá trị cho RadioButton
 	            if (gioiTinh.equalsIgnoreCase("Nam")) {
 	                gtnam.setSelected(true);
 	            } else if (gioiTinh.equalsIgnoreCase("Nữ")) {
 	                gtnu.setSelected(true);
 	            }
 	        }
 	    });
    }//GEN-LAST:event_bangthongtinAncestorAdded


	private void luuKhachHangMoi() {
		String maKH = maKHtxt.getText();
		String hoTen = hovatentxt.getText();
		String soDienThoai = sodienthoaitxt.getText();
		String email = emailtxt.getText();
		String gioiTinh = gtnam.isSelected() ? "Nam" : "Nữ";
		String cccd = cccdtxt.getText();
		 if (maKH.isEmpty() || hoTen.isEmpty() || soDienThoai.isEmpty() || email.isEmpty() || cccd.isEmpty()) {
		        JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin!", "Lỗi", JOptionPane.ERROR_MESSAGE);
		        return; // Nếu có trường trống thì không tiếp tục
		    }
		// Tạo đối tượng khách hàng mới
		KhachHang khachHang = new KhachHang(maKH, hoTen, soDienThoai, email, gioiTinh, cccd);
		// Thêm vào danh sách
		listKhachHang.add(khachHang);

		// Cập nhật model

//        JOptionPane.showMessageDialog(this, "Thêm khách hàng thành công!");
		if (dao_KhachHang.themKhachHang(khachHang)) {
			// Hiển thị thông báo và cập nhật giao diện nếu thành công
			JOptionPane.showMessageDialog(this, "Thêm khách hàng thành công!");
			model.addRow(new Object[] { maKH, hoTen, soDienThoai, email, gioiTinh, cccd });
			duaDuLieuVaoModule(); // Cập nhật dữ liệu lên JTable
		} else {
			JOptionPane.showMessageDialog(this, "Thêm khách hàng thất bại!");
		}
	}
	

	public String phatSinhMaKhachHang() {
		int maxMa = 0;

		// Duyệt qua danh sách để tìm mã lớn nhất
		for (KhachHang kh : listKhachHang) {
			String ma = kh.getMaKH(); // Ví dụ: KH001
			int so = Integer.parseInt(ma.substring(2)); // Lấy số 001 và chuyển sang số nguyên
			if (so > maxMa) {
				maxMa = so;
			}
		}

		// Tăng số lớn nhất lên 1 và tạo mã mới
		int maMoi = maxMa + 1;
		return String.format("KH%03d", maMoi); // Định dạng thành KHxxx (ví dụ: KH002)
	}

	private void nuttimActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_nuttimActionPerformed
		// Lấy giá trị từ text field
		String soDienThoaiTimKiem = timkiemtxt.getText().trim();

		// Xóa dữ liệu cũ trên model
		model.setRowCount(0);

		// Lọc danh sách khách hàng
		for (KhachHang khachHang : listKhachHang) {
			if (khachHang.getSoDienThoai().equals(soDienThoaiTimKiem)) {
				// Thêm khách hàng khớp vào model
				model.addRow(new Object[] { khachHang.getMaKH(), khachHang.getHoTen(), khachHang.getSoDienThoai(),
						khachHang.getEmail(), khachHang.getGioiTinh(), khachHang.getCccd() });
			}
		}

		// Kiểm tra nếu không tìm thấy kết quả
		if (model.getRowCount() == 0) {
			JOptionPane.showMessageDialog(this, "Không tìm thấy khách hàng với số điện thoại: " + soDienThoaiTimKiem,
					"Thông báo", JOptionPane.INFORMATION_MESSAGE);
		}
	}// GEN-LAST:event_nuttimActionPerformed

	private void themActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_themActionPerformed
		String maKhachHangMoi = phatSinhMaKhachHang();
		maKHtxt.setText(maKhachHangMoi); // Gán vào text field
		luuKhachHangMoi();
	}// GEN-LAST:event_themActionPerformed

	private void xoaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_xoaActionPerformed
		// TODO add your handling code here:

		int selectedRow = bangthongtin.getSelectedRow(); // Lấy chỉ mục dòng đã chọn
		if (selectedRow != -1) {
			// Lấy mã khách hàng từ cột trong JTable, giả sử mã khách hàng ở cột 0
			String maKhachHang = bangthongtin.getValueAt(selectedRow, 0).toString();
			// Gọi phương thức xóa khách hàng khỏi cơ sở dữ liệu
			boolean result = dao_KhachHang.xoaKhachHang(maKhachHang);
//			 for (int i = 0; i < listKhachHang.size(); i++) {
//		            KhachHang kh = listKhachHang.get(i);
//		            if (kh.getMaKH().equals(maKhachHang)) {
//		                listKhachHang.remove(i);
//		                break;  // Thoát khỏi vòng lặp sau khi tìm thấy và xóa khách hàng
//		            }
//			 }
			if (result) {
				listKhachHang = dao_KhachHang.getallTBKhachHang();
				// Nếu xóa thành công, xóa khách hàng khỏi bảng (model)
				DefaultTableModel model = (DefaultTableModel) bangthongtin.getModel();
				model.removeRow(selectedRow); // Xóa dòng khỏi bảng

				JOptionPane.showMessageDialog(null, "Khách hàng đã được xóa thành công!");
			} else {
				JOptionPane.showMessageDialog(null, "Không thể xóa khách hàng.");
			}
		} else {
			JOptionPane.showMessageDialog(null, "Vui lòng chọn một khách hàng để xóa.");
		}
	}// GEN-LAST:event_xoaActionPerformed

	// Đưa dữ liệu vào module của table
	public void duaDuLieuVaoModule() {
		model.setRowCount(0);
		for (KhachHang khachHang : listKhachHang) {
			model.addRow(new Object[] { khachHang.getMaKH(), khachHang.getHoTen(), khachHang.getSoDienThoai(),
					khachHang.getEmail(), khachHang.getGioiTinh(), khachHang.getCccd() });
		}
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CCCD;
    private javax.swing.JPanel ThongtinKH;
    private javax.swing.JTable bangthongtin;
    private javax.swing.JPanel buttontxs;
    private javax.swing.JButton capnhat;
    private javax.swing.JTextField cccdtxt;
    private javax.swing.JPanel content;
    private javax.swing.JLabel email;
    private javax.swing.JTextField emailtxt;
    private javax.swing.ButtonGroup gender;
    private javax.swing.JLabel gioitinh;
    private javax.swing.JRadioButton gtnam;
    private javax.swing.JRadioButton gtnu;
    private javax.swing.JPanel header;
    private javax.swing.JTextField hovatentxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel maKH;
    private javax.swing.JTextField maKHtxt;
    private javax.swing.JButton nutDatLai;
    private javax.swing.JButton nuttim;
    private javax.swing.JLabel sodienthoai;
    private javax.swing.JTextField sodienthoaitxt;
    private javax.swing.JButton them;
    private javax.swing.JLabel timkiem;
    private javax.swing.JTextField timkiemtxt;
    private javax.swing.JButton xoa;
    // End of variables declaration//GEN-END:variables
}
