/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.util.ArrayList;

import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

import DAO.DAO_VeMayBay;
import ENTITY.ChiTietVe;
import ENTITY.VeMayBay;

/**
 *
 * @author ADMIN
 */
public class GUI_InVe extends javax.swing.JFrame {
	private ArrayList<ChiTietVe> chiTietVeIn;
	//dao 
	private DAO_VeMayBay dao_VeMayBay = new DAO_VeMayBay(); 
	
	// Ten Bien
	private String maVe; 
	
	
	/**
	 * Creates new form GUI_InVe
	 */
	public GUI_InVe(ArrayList<ChiTietVe> chiTietVeIn, String maVe) {
		this.chiTietVeIn = chiTietVeIn;
		this.maVe = maVe; 
		
		initComponents();
		inVe();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelChinh = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(0, 0));

        panelChinh.setPreferredSize(new java.awt.Dimension(1000, 1000));
        panelChinh.setLayout(new java.awt.GridLayout(0, 1));
        getContentPane().add(panelChinh, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

	
	private void inVe() {
		VeMayBay vmb = dao_VeMayBay.getOneObjVeMayBay(maVe); 
		
        // Duyệt qua danh sách ChiTietVe và tạo panel cho từng vé
        for (ChiTietVe chiTietVe : chiTietVeIn) {
        	Form_Ve vePanel = new Form_Ve(vmb, chiTietVe); 
            panelChinh.add(vePanel);
        }
	}
	
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelChinh;
    // End of variables declaration//GEN-END:variables
}
